**SHINTA AULIA SEPTIANI - 1800015054**

##**MATRIKS DAN PYTHON NUMPY**

#1.Membuat Numpy Array

NumPy adalah singkatan dari Numerical Python yang merupakan salah satu library terpenting dalam bahasa pemrograman python. Manipulasi NumPy array mirip dengan manipulasi data pada python. Beberapa manipulasi array dasar adalah atribut array, pengindeksan array, pembentukan baris, dan penggabungan-pemisahan array. Maksud dari atribut array adalah menentukan ukuran, bentuk, dan mengatur nilai elemen individu array. Pengindeksan array berguna untuk mendapatkan dan mengatur nilai elemen individu pada array. Manipulasi array yang juga banyak digunakan adalah menggabungkan beberapa array menjadi satu atau memisahkan satu array menjadi beberapa bagian. 

Library NumPy digunakan untuk memproses array. Array NumPy adalah objek array berdimensi-N yang kuat dan digunakan pada aljabar linier, transformasi fourier, dan bilangan acak. Array dibagi menjadi dua jenis, yaitu array satu dimensi dan array multi dimensi. Array satu dimensi adalah jenis array linier, sedangkan array multidimensi adalah data dalam bentuk array yang disimpan dalam bentuk tabel. 

mengimpor library numpy

In [2]:
import numpy as np

In [44]:
#membuat array
x = np.array([1,2,3,4,5,6,7,8])
print(x)
print()
print(x.shape) # ukuran array
print()
print(x.dtype) # tipe data elemen array
print()

print(x.ndim)
print()
print(x.size) # jumlah elemen
print()
print(x.itemsize) # ukuran bit untuk masing-masing elemen

[1 2 3 4 5 6 7 8]

(8,)

int64

1

8

8


In [4]:
# mengubah array 1 × 1 menjadi array 5 × 2
z = np.array(range(10))
z = z.reshape(5,2)
z

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

#2.Vektor dengan Numpy Array

In [45]:
# membuat vector
a = np.array([1,2,3])
b = np.array([1.5, 2.5, 3.5])

# membuat vector dengan range
c = np.arange(1,10,3)

print(a)
print()
print(b)
print()
print(c)

[1 2 3]

[1.5 2.5 3.5]

[1 4 7]


#3.Operasi vektor  (Penjumlahan, Pengurangan, Perkalian dengan Scalar)

In [46]:
a = np.array([1,2,3])
b = np.array([1.5, 2.5, 3.5])

penjumlahan = a + b

pengurangan = a - b

perkalianscalar = 5 * a

print(penjumlahan)
print()
print(pengurangan)
print()
print(perkalianscalar)

[2.5 4.5 6.5]

[-0.5 -0.5 -0.5]

[ 5 10 15]


#4.Matriks dengan Numpy Array

In [47]:
#array multidimensi / matriks
#dua dimensi
y = np.array([[1, 2, 3],[2, 1, 1]], float)
print (y)
print()

#tiga dimensi
z = np.array([[1,2,5],[5,7,2],[3,1,2]])
print(z)

[[1. 2. 3.]
 [2. 1. 1.]]

[[1 2 5]
 [5 7 2]
 [3 1 2]]


In [48]:
# matrix dengan nilai nol
aa = np.zeros((3,3))

# matrix dengan nilai satu
ab = np.ones((3,3))

# matrix identitas
a1 = np.identity(3)
a2 = np.eye(3)

print(aa)
print()
print(ab)
print()
print(a1)
print()
print(a2)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#5.Operasi Matriks(Penjumlahan, Pengurangan, Perkalian dengan Scalar,Perkalian Matriks)

In [49]:
y = np.array([[1, 2],[1, 1]])
z = np.array([[8, 2],[3, 6]])

#penjumlahan
a = y+z
print(a)
print()

#pengurangan
b = y-z
print(b)
print()

#perkalian dengan skalar
c = 2*z
print(c)
print()

#perkalian matriks
d = y*z
print(d)
print()

#perkalian matriks
e = np.multiply(y,z)
print(e)

[[9 4]
 [4 7]]

[[-7  0]
 [-2 -5]]

[[16  4]
 [ 6 12]]

[[8 4]
 [3 6]]

[[8 4]
 [3 6]]


penjumlahan dan pengurangan dapat juga dicari seperti berikut.

In [50]:
y = np.array([[1, 2],[1, 1]])
z = np.array([[8, 2],[3, 6]])

#penjumlahan
a = np.add(y,z)
print(a)
print()

#pengurangan
b = np.subtract(y,z)
print(b)

[[9 4]
 [4 7]]

[[-7  0]
 [-2 -5]]


#6.Dot Product dan Cross Product 

In [51]:
y = np.array([[1, 2],[1, 1]])
z = np.array([[8, 2],[3, 6]])

#perkalian dot
X1 = np.dot(y,z)
print(X1)
print()

#perkalian cross
X2 = np.cross(y,z)
print(X2)

[[14 14]
 [11  8]]

[-14   3]


#7.Aljabar Linear dengan Numpy (Inverse Matriks, Determinan, Mengambil Elemen Diagonal, Solve Persamaan Linear)

In [23]:
a = np.array([[5,7],[1,9]])
A = np.array([2,3])

# determinant
b = np.linalg.det(a)
print(b)
print()

# inverse
c = np.linalg.inv(a)
print(c)
print()

#mengambil elemen diagonal
d = np.diag(a)
print(d)
print()

#solve persamaan linier
solusi = np.dot(c,A)
print(solusi)

37.99999999999999

[[ 0.23684211 -0.18421053]
 [-0.02631579  0.13157895]]

[5 9]

[-0.07894737  0.34210526]


#8.Principal Component Analysis dengan Numpy

In [37]:
import pandas as pd
import numpy as np
import random

data = {'a': [random.uniform(0, 1) for i in range(100)],
        'b': [random.uniform(0, 1) for i in range(100)],
        'c': [random.uniform(0, 1) for i in range(100)],
        'd': [random.uniform(0, 1) for i in range(100)],
        'e': [random.uniform(0, 1) for i in range(100)],
        'f': [random.uniform(0, 1) for i in range(100)],
        'g': [random.uniform(0, 1) for i in range(100)],
        'h': [random.uniform(0, 1) for i in range(100)],
        'i': [random.uniform(0, 1) for i in range(100)],
        'j': [random.uniform(0, 1) for i in range(100)],
        'k': [random.uniform(0, 1) for i in range(100)],
        'l': [random.uniform(0, 1) for i in range(100)],
        'label': [random.choice(['A', 'B', 'C']) for i in range(100)]}

df = pd.DataFrame(data)
df.head()

a         b         c         d  ...         j         k         l  label
0  0.981070  0.457769  0.078663  0.030306  ...  0.148829  0.282122  0.411113      C
1  0.254483  0.910400  0.531778  0.021052  ...  0.331463  0.045234  0.683281      C
2  0.795833  0.199612  0.784202  0.128299  ...  0.729698  0.078452  0.050221      C
3  0.261033  0.645742  0.585638  0.611511  ...  0.509291  0.496850  0.254882      A
4  0.302716  0.332974  0.569827  0.026068  ...  0.638482  0.985855  0.108481      C

[5 rows x 13 columns]

Kemudian kita pisahkan kolom fitur dan label seperti di bawah ini.

In [38]:
x = df.iloc[:,:-1]
x.head()

a         b         c  ...         j         k         l
0  0.981070  0.457769  0.078663  ...  0.148829  0.282122  0.411113
1  0.254483  0.910400  0.531778  ...  0.331463  0.045234  0.683281
2  0.795833  0.199612  0.784202  ...  0.729698  0.078452  0.050221
3  0.261033  0.645742  0.585638  ...  0.509291  0.496850  0.254882
4  0.302716  0.332974  0.569827  ...  0.638482  0.985855  0.108481

[5 rows x 12 columns]

In [39]:
y = df.iloc[:,-1]
y.head()

0    C
1    C
2    C
3    A
4    C
Name: label, dtype: object

Setelah fitur dan label dipisahkan, selanjutnya mari kita terapkan reduksi dimensi pada dataframe tersebut menggunakan PCA 

Principal Component Analysis atau PCA adalah teknik reduksi dimensi yang paling populer. Teknik ini menggunakan operasi matriks sederhana dari aljabar linier dan statistik untuk menghitung proyeksi dari data asli ke dalam dimensi dengan jumlah yang sama atau lebih sedikit.

Di Python, kita dapat melakukan kalkulasi Principal Component Analysis dengan class PCA() yang ada di library Scikit-Learn.

Pertama kita harus mengimpor library-nya terlebih dahulu.

In [40]:
from sklearn.decomposition import PCA

Kemudian kita membuat class PCA() dengan memberikan parameter n_components yang mendefinisikan jumlah komponen atau kolom baru yang diinginkan.

In [41]:
pca = PCA(n_components=2)

Setelah membuat class, kita lakukan fit_transform pada data fitur. Jadi, nantinya 12 kolom fitur di atas akan diproses menggunakan teknik PCA sehingga akan mengeluarkan 2 kolom baru hasil reduksi.

In [42]:
fit_pca = pca.fit_transform(x)

Selanjutnya kita buat dataframe baru hasil fit_transform tersebut.

In [43]:
pca_df = pd.DataFrame(data = fit_pca, columns = ['PCA_1', 'PCA_2'])
pca_df.tail()

PCA_1     PCA_2
95  0.185178 -0.342873
96  0.074655 -0.529028
97  0.433207  0.260420
98 -0.082755  0.369548
99 -0.336611  0.061324

Sekarang fitur-fitur dalam dataset tersebut sudah direduksi menjadi hanya 2 fitur.